/////////////////////////////////////
// FILE GENERATED BY TEXTUREPACKER //
/////////////////////////////////////

using System.Collections.Generic;

public partial class Sprite
{
	const int textureWidth = 512;
	const int textureHeight = 512;
	static readonly Dictionary<string, SpriteData> spritesData = new Dictionary<string, SpriteData> ()
	{
		{"0_TexturePacker", new SpriteData {x =  2, y = 206, width = 100, height = 100}},
		{"1_TexturePacker", new SpriteData {x =  2, y = 104, width = 100, height = 100}},
		{"Apple", new SpriteData {x =  2, y = 308, width = 80, height = 79}},
		{"Banana", new SpriteData {x =  2, y = 389, width = 100, height = 52}},
		{"Strawberry", new SpriteData {x =  2, y = 443, width = 70, height = 50}},
		{"Test", new SpriteData {x =  2, y = 2, width = 100, height = 100}},
	};
}
