/////////////////////////////////////
// FILE GENERATED BY TEXTUREPACKER //
/////////////////////////////////////

using System.Collections.Generic;

public partial class Sprite
{
	const int textureWidth = 512;
	const int textureHeight = 512;
	static readonly Dictionary<string, SpriteData> spritesData = new Dictionary<string, SpriteData> ()
	{
		{"0_TexturePacker", new SpriteData {x =  96, y = 2, width = 100, height = 100}},
		{"1_TexturePacker", new SpriteData {x =  2, y = 326, width = 100, height = 100}},
		{"BeltConnector", new SpriteData {x =  2, y = 428, width = 6, height = 6}},
		{"Item0", new SpriteData {x =  2, y = 218, width = 92, height = 106}},
		{"Item1", new SpriteData {x =  2, y = 110, width = 92, height = 106}},
		{"Item2", new SpriteData {x =  2, y = 2, width = 92, height = 106}},
	};
}
