/////////////////////////////////////
// FILE GENERATED BY TEXTUREPACKER //
/////////////////////////////////////

using System.Collections.Generic;

public partial class Sprite
{
	const int textureWidth = 512;
	const int textureHeight = 512;
	static readonly Dictionary<string, SpriteData> spritesData = new Dictionary<string, SpriteData> ()
	{
		{"0_TexturePacker", new SpriteData {x =  154, y = 116, width = 100, height = 100}},
		{"1_TexturePacker", new SpriteData {x =  272, y = 115, width = 100, height = 100}},
		{"ControlPoint", new SpriteData {x =  374, y = 177, width = 37, height = 33}},
		{"Dot", new SpriteData {x =  477, y = 177, width = 29, height = 28}},
		{"Node-0", new SpriteData {x =  390, y = 2, width = 115, height = 115}},
		{"Node-1", new SpriteData {x =  154, y = 2, width = 116, height = 112}},
		{"Node-2", new SpriteData {x =  272, y = 2, width = 116, height = 111}},
		{"Node-3", new SpriteData {x =  2, y = 2, width = 150, height = 118}},
		{"Node-4", new SpriteData {x =  442, y = 119, width = 58, height = 56}},
		{"Node-999", new SpriteData {x =  382, y = 119, width = 58, height = 56}},
		{"PageBoundary", new SpriteData {x =  374, y = 115, width = 6, height = 6}},
		{"PageCurrent", new SpriteData {x =  445, y = 177, width = 30, height = 28}},
		{"PageOther", new SpriteData {x =  413, y = 177, width = 30, height = 30}},
	};
}
