/////////////////////////////////////
// FILE GENERATED BY TEXTUREPACKER //
/////////////////////////////////////

using System.Collections.Generic;

public partial class Sprite
{
	const int textureWidth = {{texture.size.width}};
	const int textureHeight = {{texture.size.height}};
	static readonly Dictionary<string, SpriteData> spritesData = new Dictionary<string, SpriteData> ()
	{{% for sprite in allSprites %}
		{"{{sprite.trimmedName}}", new SpriteData {x =  {{sprite.frameRect.x}}, y = {{sprite.frameRect.y}}, width = {{sprite.frameRect.width}}, height = {{sprite.frameRect.height}}}},{% endfor %}
	};
}
