/////////////////////////////////////
// FILE GENERATED BY TEXTUREPACKER //
/////////////////////////////////////

using System.Collections.Generic;

public partial class Sprite
{
	const int textureWidth = 1024;
	const int textureHeight = 1024;
	static readonly Dictionary<string, SpriteData> spritesData = new Dictionary<string, SpriteData> ()
	{
		{"0_TexturePacker", new SpriteData {x =  308, y = 818, width = 100, height = 100}},
		{"1_TexturePacker", new SpriteData {x =  308, y = 716, width = 100, height = 100}},
		{"2C", new SpriteData {x =  308, y = 614, width = 100, height = 100}},
		{"2D", new SpriteData {x =  308, y = 512, width = 100, height = 100}},
		{"2H", new SpriteData {x =  308, y = 410, width = 100, height = 100}},
		{"2S", new SpriteData {x =  308, y = 308, width = 100, height = 100}},
		{"3C", new SpriteData {x =  920, y = 206, width = 100, height = 100}},
		{"3D", new SpriteData {x =  818, y = 206, width = 100, height = 100}},
		{"3H", new SpriteData {x =  716, y = 206, width = 100, height = 100}},
		{"3S", new SpriteData {x =  614, y = 206, width = 100, height = 100}},
		{"4C", new SpriteData {x =  512, y = 206, width = 100, height = 100}},
		{"4D", new SpriteData {x =  410, y = 206, width = 100, height = 100}},
		{"4H", new SpriteData {x =  308, y = 206, width = 100, height = 100}},
		{"4S", new SpriteData {x =  206, y = 920, width = 100, height = 100}},
		{"5C", new SpriteData {x =  206, y = 818, width = 100, height = 100}},
		{"5D", new SpriteData {x =  206, y = 716, width = 100, height = 100}},
		{"5H", new SpriteData {x =  206, y = 614, width = 100, height = 100}},
		{"5S", new SpriteData {x =  206, y = 512, width = 100, height = 100}},
		{"6C", new SpriteData {x =  206, y = 410, width = 100, height = 100}},
		{"6D", new SpriteData {x =  206, y = 308, width = 100, height = 100}},
		{"6H", new SpriteData {x =  206, y = 206, width = 100, height = 100}},
		{"6S", new SpriteData {x =  920, y = 104, width = 100, height = 100}},
		{"7C", new SpriteData {x =  818, y = 104, width = 100, height = 100}},
		{"7D", new SpriteData {x =  716, y = 104, width = 100, height = 100}},
		{"7H", new SpriteData {x =  614, y = 104, width = 100, height = 100}},
		{"7S", new SpriteData {x =  512, y = 104, width = 100, height = 100}},
		{"8C", new SpriteData {x =  410, y = 104, width = 100, height = 100}},
		{"8D", new SpriteData {x =  308, y = 104, width = 100, height = 100}},
		{"8H", new SpriteData {x =  206, y = 104, width = 100, height = 100}},
		{"8S", new SpriteData {x =  104, y = 920, width = 100, height = 100}},
		{"9C", new SpriteData {x =  104, y = 818, width = 100, height = 100}},
		{"9D", new SpriteData {x =  104, y = 716, width = 100, height = 100}},
		{"9H", new SpriteData {x =  104, y = 614, width = 100, height = 100}},
		{"9S", new SpriteData {x =  104, y = 512, width = 100, height = 100}},
		{"AC", new SpriteData {x =  104, y = 410, width = 100, height = 100}},
		{"AD", new SpriteData {x =  104, y = 308, width = 100, height = 100}},
		{"AH", new SpriteData {x =  104, y = 206, width = 100, height = 100}},
		{"AS", new SpriteData {x =  104, y = 104, width = 100, height = 100}},
		{"JC", new SpriteData {x =  920, y = 2, width = 100, height = 100}},
		{"JD", new SpriteData {x =  818, y = 2, width = 100, height = 100}},
		{"JH", new SpriteData {x =  716, y = 2, width = 100, height = 100}},
		{"JS", new SpriteData {x =  614, y = 2, width = 100, height = 100}},
		{"KC", new SpriteData {x =  512, y = 2, width = 100, height = 100}},
		{"KD", new SpriteData {x =  410, y = 2, width = 100, height = 100}},
		{"KH", new SpriteData {x =  308, y = 2, width = 100, height = 100}},
		{"KS", new SpriteData {x =  206, y = 2, width = 100, height = 100}},
		{"QC", new SpriteData {x =  104, y = 2, width = 100, height = 100}},
		{"QD", new SpriteData {x =  2, y = 920, width = 100, height = 100}},
		{"QH", new SpriteData {x =  2, y = 818, width = 100, height = 100}},
		{"QS", new SpriteData {x =  2, y = 716, width = 100, height = 100}},
		{"TC", new SpriteData {x =  2, y = 614, width = 100, height = 100}},
		{"TD", new SpriteData {x =  2, y = 512, width = 100, height = 100}},
		{"TH", new SpriteData {x =  2, y = 410, width = 100, height = 100}},
		{"TS", new SpriteData {x =  2, y = 308, width = 100, height = 100}},
		{"WB", new SpriteData {x =  2, y = 206, width = 100, height = 100}},
		{"WR", new SpriteData {x =  2, y = 104, width = 100, height = 100}},
		{"bar", new SpriteData {x =  308, y = 920, width = 100, height = 25}},
		{"highlight", new SpriteData {x =  2, y = 2, width = 100, height = 100}},
	};
}
